/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.time.LocalDate;
import model.Car;
import model.CarFleet;

/**
 *
 * @author nidhitiwari
 */
        
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    CarFleet carFleetDetails;
    
    public MainJFrame() {
        initComponents();
        
        carFleetDetails = new CarFleet();
        setCarFleetDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCreate.setText("Create Car");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setText("View Car");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnCreate)
                .addGap(35, 35, 35)
                .addComponent(btnView)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewPanel = new ViewJPanel(carFleetDetails);
        splitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CreateJPanel createPanel = new CreateJPanel(carFleetDetails);
        splitPane.setRightComponent(createPanel);
    }//GEN-LAST:event_btnCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    
    public void setCarFleetDetails(){
     
        Car c = carFleetDetails.addNewCar();
       
        c.setSerialNumber(92134);
        c.setModelNumber(20987);
        c.setManufacturer("Tesla");
        c.setManufacturedDate(LocalDate.parse("2018-12-02"));
        c.setSeatCapacity(4);
        c.setUsedByApp("Uber");
        c.setIsAvailable(true);
        c.setLastUpdated(LocalDate.parse("2020-11-12"));
        c.setMaintenanceCertExpDate(LocalDate.parse("2025-09-11"));
        c.setCity("Boston");
       
             
        Car c1 = carFleetDetails.addNewCar();
       
        c1.setSerialNumber(92135);
        c1.setModelNumber(20890);
        c1.setManufacturer("BMW");
        c1.setManufacturedDate(LocalDate.parse("2015-02-12"));
        c1.setSeatCapacity(5);
        c1.setUsedByApp("Lyft");
        c1.setIsAvailable(true);
        c1.setLastUpdated(LocalDate.parse("2021-12-02"));
        c1.setMaintenanceCertExpDate(LocalDate.parse("2020-09-11"));
        c1.setCity("NewYork");
             
        Car c2 = carFleetDetails.addNewCar();
       
        c2.setSerialNumber(92136);
        c2.setModelNumber(20990);
        c2.setManufacturer("Suzuki");
        c2.setManufacturedDate( LocalDate.parse("2000-12-02"));
        c2.setSeatCapacity(4);
        c2.setUsedByApp("Ola");
        c2.setIsAvailable(true);
        c2.setLastUpdated(LocalDate.parse("2021-08-02"));
        c2.setMaintenanceCertExpDate(LocalDate.parse("2020-09-05"));
        c2.setCity("Cali");
       
        Car c3 = carFleetDetails.addNewCar();
       
        c3.setSerialNumber(92198);
        c3.setModelNumber(20156);
        c3.setManufacturer("Toyota");
        c3.setManufacturedDate( LocalDate.parse("2000-02-12"));
        c3.setSeatCapacity(5);
        c3.setUsedByApp("Uber");
        c3.setIsAvailable(false);
        c3.setLastUpdated(LocalDate.parse("2021-02-11"));
        c3.setMaintenanceCertExpDate(LocalDate.parse("2021-09-11"));
        c3.setCity("Texas");
       
        Car c4 = carFleetDetails.addNewCar();
       
        c4.setSerialNumber(92145);
        c4.setModelNumber(20789);
        c4.setManufacturer("Tesla");
        c4.setManufacturedDate(LocalDate.parse("2018-12-02"));
        c4.setSeatCapacity(7);
        c4.setUsedByApp("Uber");
        c4.setIsAvailable(true);
        c4.setLastUpdated(LocalDate.parse("2020-11-12"));
        c4.setMaintenanceCertExpDate(LocalDate.parse("2025-09-11"));
        c4.setCity("Texas");
     
        Car c5 = carFleetDetails.addNewCar();
       
        c5.setSerialNumber(93456);
        c5.setModelNumber(20789);
        c5.setManufacturer("Honda");
        c5.setManufacturedDate( LocalDate.parse("2018-09-02"));
        c5.setSeatCapacity(8);
        c5.setUsedByApp("Uber");
        c5.setIsAvailable(false);
        c5.setLastUpdated(LocalDate.parse("2020-05-10"));
        c5.setMaintenanceCertExpDate(LocalDate.parse("2026-03-07"));
        c5.setCity("Boston");      
           
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
